### ISSUE TITLE
Question about Regularization term in paper

### ISSUE THREAD

**Issue by zhangletian2** [zzwdx1234/MEDIC#1]
It's quite a inspiring work, I really appreciate it, but I have some question about the implementation.
In the paper, there is a regularization term "L_reg" in Sec3.2, but it doesn't appear in the Algorithm mention in the paper, and there isn't any in the released code either.
Is there any clues that I overlooked? I'll be appreciated for your reply!

**Comment by zzwdx** [comment]
Thank you for your question! I apologize for the delay in responding. The regularization term in equation 6 doesn't require explicit computation as it is derived from our original meta-objective. Specifically, equation 5 is the result of the Taylor expansion of equation 1, and equation 6 is the expansion of the second term in equation 5.

**Comment by zhangletian2** [comment]
Thanks!
